# Site settings
port: 4000
title: PConstants in JRuby
email: mamba2928@yahoo.co.uk
description: > # this means to ignore newlines until "baseurl:"
  This project can serve as tutorial for polyglot maven, and the use of Java
  constants in JRuby (particulary in JRubyArt and propane)
baseurl: "" # the subpath of your site, e.g. /blog
regenerate: true
url: "https://ruby-processing.github.io/PConstants"

urls:
  bugs: https://github.com/ruby-processing/PConstants/issues
  github: https://github.com/ruby-processing/PConstants/
twitter_username: monkstoneT
github_username:  monkstone

syntax-highlighting:
  enabled: true
# Build settings
markdown: kramdown
